### PR TITLE
ability cost

### PR DESCRIPTION
**Pull request by dazdya**
added ability_cost: !!null to all spells.

### CODE REVIEW

**Comment by dazdya** [comment]
Ik heb het gevoel dat ik erg sloppy werk. Ik merk soms niet in welke branch ik werk. Ik moet hier erg aan wennen, maar ik leer.

**Comment by nihlaeth** [comment]
It doesn't look sloppy to me. It's normal, even encouraged to need several commits to get to the final format.

**Comment by nihlaeth** [comment]
I see what you mean with the branch names now, but that information is not preserved when I finally merge it, so don't worry about it.

**Comment by nihlaeth** [comment]
I really shouldn't be merging when I've already taken my sleep medication... I just now noticed that the work you did on the powers is not complete yet. No matter, there is no backend for that in place yet so it won't break anything.

**Comment by dazdya** [comment]
Glad to hear I'm not the only one making mistakes. But the powers are done now.

**Pull request merged**
